# .streamlit/secrets.toml

[connections.sqlite]
# The URL for an SQLite connection: 
# sqlite:/// - specifies the database type (SQLite) and a file path.
# analytics.db - the name of the file that will be created and store your data.
url = "sqlite:///analytics.db"